export const muscleGroups = [
  'Pecho',
  'Espalda',
  'Hombros',
  'Bíceps',
  'Tríceps',
  'Antebrazos',
  'Cuádriceps',
  'Isquiotibiales',
  'Glúteos',
  'Gemelos',
  'Core',
  'Cardio',
] as const;

export type MuscleGroup = (typeof muscleGroups)[number];
export type ActivityKind = 'strength' | 'cardio';

export const equipmentTypes = [
  'Barra',
  'Mancuernas',
  'Máquina',
  'Polea',
  'Peso corporal',
  'Kettlebell',
  'Bandas',
  'Smith',
  'Landmine',
  'Cinta de correr',
  'Bicicleta estática',
  'Bicicleta exterior',
  'Elíptica',
  'Remo ergómetro',
  'Escaladora',
  'Air bike',
  'Cuerda',
  'Piscina',
  'SkiErg',
  'Sin equipo',
] as const;

export type EquipmentType = (typeof equipmentTypes)[number];
export type LibraryExercise = { name: string; group: MuscleGroup; equipment: EquipmentType; kind: ActivityKind };
type CatalogExercise = Omit<LibraryExercise, 'group' | 'kind'> & { kind?: ActivityKind };

const exerciseCatalog = {
  Pecho: [
    { name: 'Press banca', equipment: 'Barra' },
    { name: 'Press banca con mancuernas', equipment: 'Mancuernas' },
    { name: 'Press inclinado con barra', equipment: 'Barra' },
    { name: 'Press inclinado con mancuernas', equipment: 'Mancuernas' },
    { name: 'Press declinado con barra', equipment: 'Barra' },
    { name: 'Press declinado con mancuernas', equipment: 'Mancuernas' },
    { name: 'Press de pecho convergente', equipment: 'Máquina' },
    { name: 'Press de pecho sentado', equipment: 'Máquina' },
    { name: 'Press banca en Smith', equipment: 'Smith' },
    { name: 'Aperturas con mancuernas', equipment: 'Mancuernas' },
    { name: 'Aperturas inclinadas con mancuernas', equipment: 'Mancuernas' },
    { name: 'Aperturas en peck deck', equipment: 'Máquina' },
    { name: 'Cruces de polea', equipment: 'Polea' },
    { name: 'Cruces de polea de abajo arriba', equipment: 'Polea' },
    { name: 'Cruces de polea de arriba abajo', equipment: 'Polea' },
    { name: 'Press de pecho en polea', equipment: 'Polea' },
    { name: 'Flexiones', equipment: 'Peso corporal' },
    { name: 'Flexiones con pies elevados', equipment: 'Peso corporal' },
    { name: 'Flexiones diamante', equipment: 'Peso corporal' },
    { name: 'Fondos para pecho', equipment: 'Peso corporal' },
    { name: 'Press de suelo', equipment: 'Barra' },
    { name: 'Press de suelo con mancuernas', equipment: 'Mancuernas' },
  ],
  Espalda: [
    { name: 'Jalón al pecho agarre amplio', equipment: 'Polea' },
    { name: 'Jalón al pecho agarre estrecho', equipment: 'Polea' },
    { name: 'Jalón supino', equipment: 'Polea' },
    { name: 'Jalón con brazos rectos', equipment: 'Polea' },
    { name: 'Dominadas pronas', equipment: 'Peso corporal' },
    { name: 'Dominadas supinas', equipment: 'Peso corporal' },
    { name: 'Dominadas asistidas', equipment: 'Máquina' },
    { name: 'Remo con barra', equipment: 'Barra' },
    { name: 'Remo Pendlay', equipment: 'Barra' },
    { name: 'Remo con mancuerna a una mano', equipment: 'Mancuernas' },
    { name: 'Remo inclinado con mancuernas', equipment: 'Mancuernas' },
    { name: 'Remo sentado en polea', equipment: 'Polea' },
    { name: 'Remo bajo con agarre neutro', equipment: 'Polea' },
    { name: 'Remo en máquina con pecho apoyado', equipment: 'Máquina' },
    { name: 'Remo iso-lateral', equipment: 'Máquina' },
    { name: 'Remo en T', equipment: 'Barra' },
    { name: 'Remo en T con apoyo', equipment: 'Máquina' },
    { name: 'Pullover con mancuerna', equipment: 'Mancuernas' },
    { name: 'Pullover en máquina', equipment: 'Máquina' },
    { name: 'Peso muerto convencional', equipment: 'Barra' },
    { name: 'Peso muerto sumo', equipment: 'Barra' },
    { name: 'Hiperextensiones', equipment: 'Peso corporal' },
  ],
  Hombros: [
    { name: 'Press militar de pie', equipment: 'Barra' },
    { name: 'Press militar sentado', equipment: 'Barra' },
    { name: 'Press de hombros con mancuernas', equipment: 'Mancuernas' },
    { name: 'Press Arnold', equipment: 'Mancuernas' },
    { name: 'Press de hombros en máquina', equipment: 'Máquina' },
    { name: 'Press de hombros en Smith', equipment: 'Smith' },
    { name: 'Elevaciones laterales con mancuernas', equipment: 'Mancuernas' },
    { name: 'Elevación lateral a una mano en polea', equipment: 'Polea' },
    { name: 'Elevaciones laterales en máquina', equipment: 'Máquina' },
    { name: 'Elevaciones frontales con disco', equipment: 'Máquina' },
    { name: 'Elevaciones frontales con mancuernas', equipment: 'Mancuernas' },
    { name: 'Remo al mentón con barra', equipment: 'Barra' },
    { name: 'Pájaros con mancuernas', equipment: 'Mancuernas' },
    { name: 'Pájaros en peck deck inverso', equipment: 'Máquina' },
    { name: 'Cruce inverso de poleas', equipment: 'Polea' },
    { name: 'Face pull', equipment: 'Polea' },
    { name: 'Press landmine a una mano', equipment: 'Landmine' },
    { name: 'Flexiones en pica', equipment: 'Peso corporal' },
  ],
  Bíceps: [
    { name: 'Curl con barra recta', equipment: 'Barra' },
    { name: 'Curl con barra EZ', equipment: 'Barra' },
    { name: 'Curl alterno con mancuernas', equipment: 'Mancuernas' },
    { name: 'Curl simultáneo con mancuernas', equipment: 'Mancuernas' },
    { name: 'Curl martillo', equipment: 'Mancuernas' },
    { name: 'Curl martillo cruzado', equipment: 'Mancuernas' },
    { name: 'Curl inclinado', equipment: 'Mancuernas' },
    { name: 'Curl concentrado', equipment: 'Mancuernas' },
    { name: 'Curl predicador con barra EZ', equipment: 'Barra' },
    { name: 'Curl predicador en máquina', equipment: 'Máquina' },
    { name: 'Curl en polea baja', equipment: 'Polea' },
    { name: 'Curl bayesiano', equipment: 'Polea' },
    { name: 'Curl araña', equipment: 'Mancuernas' },
    { name: 'Curl de arrastre', equipment: 'Barra' },
    { name: 'Curl con bandas', equipment: 'Bandas' },
    { name: 'Curl con kettlebell', equipment: 'Kettlebell' },
  ],
  Tríceps: [
    { name: 'Extensión de tríceps en polea', equipment: 'Polea' },
    { name: 'Extensión con cuerda en polea', equipment: 'Polea' },
    { name: 'Extensión de tríceps por encima de la cabeza', equipment: 'Polea' },
    { name: 'Extensión unilateral en polea', equipment: 'Polea' },
    { name: 'Patada de tríceps con mancuerna', equipment: 'Mancuernas' },
    { name: 'Press francés con barra EZ', equipment: 'Barra' },
    { name: 'Press francés con mancuernas', equipment: 'Mancuernas' },
    { name: 'Extensión tumbado rompecráneos', equipment: 'Barra' },
    { name: 'Press banca agarre cerrado', equipment: 'Barra' },
    { name: 'Fondos en paralelas para tríceps', equipment: 'Peso corporal' },
    { name: 'Extensión de tríceps en máquina', equipment: 'Máquina' },
    { name: 'Flexiones diamante', equipment: 'Peso corporal' },
    { name: 'Extensión con banda', equipment: 'Bandas' },
    { name: 'Press JM', equipment: 'Barra' },
  ],
  Antebrazos: [
    { name: 'Curl de muñeca supino', equipment: 'Barra' },
    { name: 'Curl de muñeca prono', equipment: 'Barra' },
    { name: 'Curl de muñeca con mancuernas', equipment: 'Mancuernas' },
    { name: 'Curl de muñeca en polea', equipment: 'Polea' },
    { name: 'Paseo del granjero', equipment: 'Mancuernas' },
    { name: 'Agarre de disco', equipment: 'Máquina' },
    { name: 'Curl inverso con barra EZ', equipment: 'Barra' },
    { name: 'Colgarse de la barra', equipment: 'Peso corporal' },
  ],
  Cuádriceps: [
    { name: 'Sentadilla trasera', equipment: 'Barra' },
    { name: 'Sentadilla frontal', equipment: 'Barra' },
    { name: 'Sentadilla goblet', equipment: 'Kettlebell' },
    { name: 'Sentadilla en multipower', equipment: 'Smith' },
    { name: 'Prensa de piernas', equipment: 'Máquina' },
    { name: 'Prensa inclinada', equipment: 'Máquina' },
    { name: 'Hack squat', equipment: 'Máquina' },
    { name: 'Extensión de cuádriceps', equipment: 'Máquina' },
    { name: 'Zancadas caminando', equipment: 'Mancuernas' },
    { name: 'Zancada búlgara', equipment: 'Mancuernas' },
    { name: 'Step-up', equipment: 'Mancuernas' },
    { name: 'Sentadilla sissy', equipment: 'Peso corporal' },
    { name: 'Sentadilla con banda', equipment: 'Bandas' },
    { name: 'Extensión unilateral de cuádriceps', equipment: 'Máquina' },
  ],
  Isquiotibiales: [
    { name: 'Curl femoral tumbado', equipment: 'Máquina' },
    { name: 'Curl femoral sentado', equipment: 'Máquina' },
    { name: 'Curl femoral a una pierna', equipment: 'Máquina' },
    { name: 'Peso muerto rumano con barra', equipment: 'Barra' },
    { name: 'Peso muerto rumano con mancuernas', equipment: 'Mancuernas' },
    { name: 'Peso muerto piernas rígidas', equipment: 'Barra' },
    { name: 'Buenos días', equipment: 'Barra' },
    { name: 'Nordic curl', equipment: 'Peso corporal' },
    { name: 'Curl femoral con fitball', equipment: 'Peso corporal' },
    { name: 'Pull-through en polea', equipment: 'Polea' },
    { name: 'Peso muerto rumano con kettlebell', equipment: 'Kettlebell' },
    { name: 'Curl femoral con banda', equipment: 'Bandas' },
  ],
  Glúteos: [
    { name: 'Hip thrust con barra', equipment: 'Barra' },
    { name: 'Hip thrust en máquina', equipment: 'Máquina' },
    { name: 'Puente de glúteo', equipment: 'Peso corporal' },
    { name: 'Puente de glúteo con barra', equipment: 'Barra' },
    { name: 'Patada de glúteo en polea', equipment: 'Polea' },
    { name: 'Patada de glúteo en máquina', equipment: 'Máquina' },
    { name: 'Abducción de cadera en máquina', equipment: 'Máquina' },
    { name: 'Abducción de cadera en polea', equipment: 'Polea' },
    { name: 'Abducción con banda', equipment: 'Bandas' },
    { name: 'Peso muerto sumo', equipment: 'Barra' },
    { name: 'Sentadilla sumo con kettlebell', equipment: 'Kettlebell' },
    { name: 'Zancada inversa', equipment: 'Mancuernas' },
    { name: 'Extensión de cadera en banco', equipment: 'Peso corporal' },
    { name: 'Monster walks', equipment: 'Bandas' },
  ],
  Gemelos: [
    { name: 'Elevación de gemelos de pie', equipment: 'Máquina' },
    { name: 'Elevación de gemelos sentado', equipment: 'Máquina' },
    { name: 'Gemelos en prensa', equipment: 'Máquina' },
    { name: 'Elevación de gemelos con barra', equipment: 'Barra' },
    { name: 'Elevación de gemelos con mancuernas', equipment: 'Mancuernas' },
    { name: 'Elevación unilateral de gemelos', equipment: 'Peso corporal' },
    { name: 'Gemelos en multipower', equipment: 'Smith' },
    { name: 'Tibial anterior', equipment: 'Peso corporal' },
  ],
  Core: [
    { name: 'Plancha frontal', equipment: 'Peso corporal' },
    { name: 'Plancha lateral', equipment: 'Peso corporal' },
    { name: 'Crunch en polea', equipment: 'Polea' },
    { name: 'Crunch en máquina', equipment: 'Máquina' },
    { name: 'Elevación de piernas colgado', equipment: 'Peso corporal' },
    { name: 'Elevación de rodillas en paralelas', equipment: 'Peso corporal' },
    { name: 'Rueda abdominal', equipment: 'Peso corporal' },
    { name: 'Pallof press', equipment: 'Polea' },
    { name: 'Woodchop en polea', equipment: 'Polea' },
    { name: 'Dead bug', equipment: 'Peso corporal' },
    { name: 'Ab wheel desde rodillas', equipment: 'Peso corporal' },
    { name: 'Russian twist con disco', equipment: 'Máquina' },
    { name: 'Leñador con banda', equipment: 'Bandas' },
    { name: 'Suitcase carry', equipment: 'Kettlebell' },
  ],
  Cardio: [
    { name: 'Correr en cinta', equipment: 'Cinta de correr', kind: 'cardio' },
    { name: 'Caminar en cinta con inclinación', equipment: 'Cinta de correr', kind: 'cardio' },
    { name: 'Intervalos de sprint en cinta', equipment: 'Cinta de correr', kind: 'cardio' },
    { name: 'Correr al aire libre', equipment: 'Sin equipo', kind: 'cardio' },
    { name: 'Caminata rápida', equipment: 'Sin equipo', kind: 'cardio' },
    { name: 'Bicicleta estática', equipment: 'Bicicleta estática', kind: 'cardio' },
    { name: 'Ciclismo indoor', equipment: 'Bicicleta estática', kind: 'cardio' },
    { name: 'Ciclismo al aire libre', equipment: 'Bicicleta exterior', kind: 'cardio' },
    { name: 'Elíptica', equipment: 'Elíptica', kind: 'cardio' },
    { name: 'Remo continuo', equipment: 'Remo ergómetro', kind: 'cardio' },
    { name: 'Intervalos en remo ergómetro', equipment: 'Remo ergómetro', kind: 'cardio' },
    { name: 'Escaladora', equipment: 'Escaladora', kind: 'cardio' },
    { name: 'Air bike', equipment: 'Air bike', kind: 'cardio' },
    { name: 'Saltar a la cuerda', equipment: 'Cuerda', kind: 'cardio' },
    { name: 'Natación continua', equipment: 'Piscina', kind: 'cardio' },
    { name: 'SkiErg', equipment: 'SkiErg', kind: 'cardio' },
    { name: 'Subir escaleras', equipment: 'Escaladora', kind: 'cardio' },
    { name: 'Marcha con rodillas altas', equipment: 'Sin equipo', kind: 'cardio' },
    { name: 'Shadow boxing', equipment: 'Sin equipo', kind: 'cardio' },
    { name: 'Circuito HIIT sin equipo', equipment: 'Sin equipo', kind: 'cardio' },
  ],
} satisfies Record<MuscleGroup, CatalogExercise[]>;

export const exerciseLibrary: LibraryExercise[] = muscleGroups.flatMap((group) =>
  exerciseCatalog[group].map((exercise) => ({
    ...exercise,
    group,
    kind: exercise.kind ?? (group === 'Cardio' ? 'cardio' : 'strength'),
  })),
);